# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eksctl < Formula
  desc "The official CLI for Amazon EKS"
  homepage "https://eksctl.io/"
  version "0.173.0"

  depends_on "aws-iam-authenticator"
  depends_on "kubernetes-cli"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yuxiang-zhang/eksctl/releases/download/v0.173.0/eksctl_Darwin_arm64.tar.gz"
      sha256 "30784ef5cf6662296df2d6fa01abe46bf65e1977042d56513d694d573bd4d58d"

      def install
        bin.install "eksctl"

        # Install bash completion
        output = Utils.popen_read("#{bin}/eksctl completion bash")
        (bash_completion/"eksctl").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/eksctl completion zsh")
        (zsh_completion/"_eksctl").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuxiang-zhang/eksctl/releases/download/v0.173.0/eksctl_Darwin_amd64.tar.gz"
      sha256 "e0095bf0c0a40c3e61e98c76d14ec1ecb85a6274eb6f5116fbc7ff6db9af2fc8"

      def install
        bin.install "eksctl"

        # Install bash completion
        output = Utils.popen_read("#{bin}/eksctl completion bash")
        (bash_completion/"eksctl").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/eksctl completion zsh")
        (zsh_completion/"_eksctl").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yuxiang-zhang/eksctl/releases/download/v0.173.0/eksctl_Linux_armv6.tar.gz"
      sha256 "2917095768fbaf38ad43b5615ff474bda5cb02f77e05719693451f41ebf8dc88"

      def install
        bin.install "eksctl"

        # Install bash completion
        output = Utils.popen_read("#{bin}/eksctl completion bash")
        (bash_completion/"eksctl").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/eksctl completion zsh")
        (zsh_completion/"_eksctl").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yuxiang-zhang/eksctl/releases/download/v0.173.0/eksctl_Linux_arm64.tar.gz"
      sha256 "436e7f80c80790b4d28003103e8381cc86e8f438a22e2c848d9812e955ec1e52"

      def install
        bin.install "eksctl"

        # Install bash completion
        output = Utils.popen_read("#{bin}/eksctl completion bash")
        (bash_completion/"eksctl").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/eksctl completion zsh")
        (zsh_completion/"_eksctl").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yuxiang-zhang/eksctl/releases/download/v0.173.0/eksctl_Linux_amd64.tar.gz"
      sha256 "6730b241450e8b53eb14da9862c498600cc6b948c5fc3a15b81ad1e6152d9da8"

      def install
        bin.install "eksctl"

        # Install bash completion
        output = Utils.popen_read("#{bin}/eksctl completion bash")
        (bash_completion/"eksctl").write output

        # Install zsh completion
        output = Utils.popen_read("#{bin}/eksctl completion zsh")
        (zsh_completion/"_eksctl").write output
      end
    end
  end

  head "https://github.com/eksctl-io/eksctl/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz"
end
